In [1]:
import numpy as np
import pandas as pd

In [11]:
interactions = pd.read_csv(
    "../data/db/banner_interactions.csv",
    parse_dates=["event_date"]
)
banners = pd.read_csv(
    "../data/db/banners.csv",
    parse_dates=["created_at"]
)

users = pd.read_csv("../data/db/users.csv")

In [6]:

TRAIN_END = pd.Timestamp("2026-02-28")
VALID_END = pd.Timestamp("2026-03-15")

# Делим данные по времени: модель видит только прошлое.
train_df = interactions[interactions["event_date"] <= TRAIN_END].copy()
valid_df = interactions[
    (interactions["event_date"] > TRAIN_END)
    & (interactions["event_date"] <= VALID_END)
].copy()
test_df = interactions[interactions["event_date"] > VALID_END].copy()

In [8]:
train_df.head()

  event_date  user_id banner_id  impressions  clicks  ctr
0 2026-01-01  u_00007    b_0082            3       0  0.0
1 2026-01-01  u_00009    b_0234            3       0  0.0
2 2026-01-01  u_00012    b_0041            4       0  0.0
3 2026-01-01  u_00012    b_0215            5       1  0.2
4 2026-01-01  u_00015    b_0210            5       2  0.4

In [9]:
valid_df.head()

      event_date  user_id banner_id  impressions  clicks  ctr
98282 2026-03-01  u_00004    b_0281            5       0  0.0
98283 2026-03-01  u_00007    b_0147            1       0  0.0
98284 2026-03-01  u_00011    b_0174            2       0  0.0
98285 2026-03-01  u_00015    b_0159            2       0  0.0
98286 2026-03-01  u_00024    b_0181            3       0  0.0

In [10]:
test_df.head()

       event_date  user_id banner_id  impressions  clicks  ctr
123117 2026-03-16  u_00001    b_0209            6       0  0.0
123118 2026-03-16  u_00003    b_0063            8       0  0.0
123119 2026-03-16  u_00003    b_0241            5       0  0.0
123120 2026-03-16  u_00007    b_0151            1       0  0.0
123121 2026-03-16  u_00008    b_0274            1       0  0.0

In [12]:
user_ids = users["user_id"].drop_duplicates().tolist()
banner_ids = banners["banner_id"].drop_duplicates().tolist()

In [14]:
user2idx = {user_id: idx for idx, user_id in enumerate(user_ids)}
item2idx = {banner_id: idx for idx, banner_id in enumerate(banner_ids)}
idx2item = {idx: banner_id for banner_id, idx in item2idx.items()}

In [17]:
item2idx

{'b_0001': 0,
 'b_0002': 1,
 'b_0003': 2,
 'b_0004': 3,
 'b_0005': 4,
 'b_0006': 5,
 'b_0007': 6,
 'b_0008': 7,
 'b_0009': 8,
 'b_0010': 9,
 'b_0011': 10,
 'b_0012': 11,
 'b_0013': 12,
 'b_0014': 13,
 'b_0015': 14,
 'b_0016': 15,
 'b_0017': 16,
 'b_0018': 17,
 'b_0019': 18,
 'b_0020': 19,
 'b_0021': 20,
 'b_0022': 21,
 'b_0023': 22,
 'b_0024': 23,
 'b_0025': 24,
 'b_0026': 25,
 'b_0027': 26,
 'b_0028': 27,
 'b_0029': 28,
 'b_0030': 29,
 'b_0031': 30,
 'b_0032': 31,
 'b_0033': 32,
 'b_0034': 33,
 'b_0035': 34,
 'b_0036': 35,
 'b_0037': 36,
 'b_0038': 37,
 'b_0039': 38,
 'b_0040': 39,
 'b_0041': 40,
 'b_0042': 41,
 'b_0043': 42,
 'b_0044': 43,
 'b_0045': 44,
 'b_0046': 45,
 'b_0047': 46,
 'b_0048': 47,
 'b_0049': 48,
 'b_0050': 49,
 'b_0051': 50,
 'b_0052': 51,
 'b_0053': 52,
 'b_0054': 53,
 'b_0055': 54,
 'b_0056': 55,
 'b_0057': 56,
 'b_0058': 57,
 'b_0059': 58,
 'b_0060': 59,
 'b_0061': 60,
 'b_0062': 61,
 'b_0063': 62,
 'b_0064': 63,
 'b_0065': 64,
 'b_0066': 65,
 'b_0067': 66,
 'b_0068': 67,
 'b_0069': 68,
 'b_0070': 69,
 'b_0071': 70,
 'b_0072': 71,
 'b_0073': 72,
 'b_0074': 73,
 'b_0075': 74,
 'b_0076': 75,
 'b_0077': 76,
 'b_0078': 77,
 'b_0079': 78,
 'b_0080': 79,
 'b_0081': 80,
 'b_0082': 81,
 'b_0083': 82,
 'b_0084': 83,
 'b_0085': 84,
 'b_0086': 85,
 'b_0087': 86,
 'b_0088': 87,
 'b_0089': 88,
 'b_0090': 89,
 'b_0091': 90,
 'b_0092': 91,
 'b_0093': 92,
 'b_0094': 93,
 'b_0095': 94,
 'b_0096': 95,
 'b_0097': 96,
 'b_0098': 97,
 'b_0099': 98,
 'b_0100': 99,
 'b_0101': 100,
 'b_0102': 101,
 'b_0103': 102,
 'b_0104': 103,
 'b_0105': 104,
 'b_0106': 105,
 'b_0107': 106,
 'b_0108': 107,
 'b_0109': 108,
 'b_0110': 109,
 'b_0111': 110,
 'b_0112': 111,
 'b_0113': 112,
 'b_0114': 113,
 'b_0115': 114,
 'b_0116': 115,
 'b_0117': 116,
 'b_0118': 117,
 'b_0119': 118,
 'b_0120': 119,
 'b_0121': 120,
 'b_0122': 121,
 'b_0123': 122,
 'b_0124': 123,
 'b_0125': 124,
 'b_0126': 125,
 'b_0127': 126,
 'b_0128': 127,
 'b_0129': 128,
 'b_0130': 129,
 'b_0131': 130,
 'b_0132': 131,
 'b_0133': 132,
 'b_0134': 133,
 'b_0135': 134,
 'b_0136': 135,
 'b_0137': 136,
 'b_0138': 137,
 'b_0139': 138,
 'b_0140': 139,
 'b_0141': 140,
 'b_0142': 141,
 'b_0143': 142,
 'b_0144': 143,
 'b_0145': 144,
 'b_0146': 145,
 'b_0147': 146,
 'b_0148': 147,
 'b_0149': 148,
 'b_0150': 149,
 'b_0151': 150,
 'b_0152': 151,
 'b_0153': 152,
 'b_0154': 153,
 'b_0155': 154,
 'b_0156': 155,
 'b_0157': 156,
 'b_0158': 157,
 'b_0159': 158,
 'b_0160': 159,
 'b_0161': 160,
 'b_0162': 161,
 'b_0163': 162,
 'b_0164': 163,
 'b_0165': 164,
 'b_0166': 165,
 'b_0167': 166,
 'b_0168': 167,
 'b_0169': 168,
 'b_0170': 169,
 'b_0171': 170,
 'b_0172': 171,
 'b_0173': 172,
 'b_0174': 173,
 'b_0175': 174,
 'b_0176': 175,
 'b_0177': 176,
 'b_0178': 177,
 'b_0179': 178,
 'b_0180': 179,
 'b_0181': 180,
 'b_0182': 181,
 'b_0183': 182,
 'b_0184': 183,
 'b_0185': 184,
 'b_0186': 185,
 'b_0187': 186,
 'b_0188': 187,
 'b_0189': 188,
 'b_0190': 189,
 'b_0191': 190,
 'b_0192': 191,
 'b_0193': 192,
 'b_0194': 193,
 'b_0195': 194,
 'b_0196': 195,
 'b_0197': 196,
 'b_0198': 197,
 'b_0199': 198,
 'b_0200': 199,
 'b_0201': 200,
 'b_0202': 201,
 'b_0203': 202,
 'b_0204': 203,
 'b_0205': 204,
 'b_0206': 205,
 'b_0207': 206,
 'b_0208': 207,
 'b_0209': 208,
 'b_0210': 209,
 'b_0211': 210,
 'b_0212': 211,
 'b_0213': 212,
 'b_0214': 213,
 'b_0215': 214,
 'b_0216': 215,
 'b_0217': 216,
 'b_0218': 217,
 'b_0219': 218,
 'b_0220': 219,
 'b_0221': 220,
 'b_0222': 221,
 'b_0223': 222,
 'b_0224': 223,
 'b_0225': 224,
 'b_0226': 225,
 'b_0227': 226,
 'b_0228': 227,
 'b_0229': 228,
 'b_0230': 229,
 'b_0231': 230,
 'b_0232': 231,
 'b_0233': 232,
 'b_0234': 233,
 'b_0235': 234,
 'b_0236': 235,
 'b_0237': 236,
 'b_0238': 237,
 'b_0239': 238,
 'b_0240': 239,
 'b_0241': 240,
 'b_0242': 241,
 'b_0243': 242,
 'b_0244': 243,
 'b_0245': 244,
 'b_0246': 245,
 'b_0247': 246,
 'b_0248': 247,
 'b_0249': 248,
 'b_0250': 249,
 'b_0251': 250,
 'b_0252': 251,
 'b_0253': 252,
 'b_0254': 253,
 'b_0255': 254,
 'b_0256': 255,
 'b_0257': 256,
 'b_0258': 257,
 'b_0259': 258,
 'b_0260': 259,
 'b_0261': 260,
 'b_0262': 261,
 'b_0263': 262,
 'b_0264': 263,
 'b_0265': 264,
 'b_0266': 265,
 'b_0267': 266,
 'b_0268': 267,
 'b_0269': 268,
 'b_0270': 269,
 'b_0271': 270,
 'b_0272': 271,
 'b_0273': 272,
 'b_0274': 273,
 'b_0275': 274,
 'b_0276': 275,
 'b_0277': 276,
 'b_0278': 277,
 'b_0279': 278,
 'b_0280': 279,
 'b_0281': 280,
 'b_0282': 281,
 'b_0283': 282,
 'b_0284': 283,
 'b_0285': 284,
 'b_0286': 285,
 'b_0287': 286,
 'b_0288': 287,
 'b_0289': 288,
 'b_0290': 289,
 'b_0291': 290,
 'b_0292': 291,
 'b_0293': 292,
 'b_0294': 293,
 'b_0295': 294,
 'b_0296': 295,
 'b_0297': 296,
 'b_0298': 297,
 'b_0299': 298,
 'b_0300': 299}